### ISSUE TITLE
Unable to add a dropped student

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#1030]
Error reported in course EVHS-APCS-A on page Nonehttps://runestone.academy/runestone/books/published/csawesome/index.html by user bhatnagars bhatnagars@esuhsd.org
I am trying to learn how to use the CS Awesome curriculum for my class coming fall. To learn the process of creating a class, adding students, and making assignments, I created a dummy student profile with the username: evteststudent and dded this username to my course. Then successfully removed the student. I was trying to add the student again, but it keeps saying that it is not a unique userid and won't let me add the student to the class. I tried doing it from the student end, but that also gives me an error. Could you guide me in how to add a student that has been previously been removed?

**Comment by bhoffman0** [comment]
I replied to your email about this. Since your dummy student account already has a Runestone account, you have to first login to that account on Runestone, then click on Sign Up on the main Runestone page (or the person icon on the top right and choose Change Course and click on Enroll in a Course at the bottom). Then, in the sign up form, type in your custom course name and click on Apply Changes. You cannot upload a csv file for students who already have Runestone accounts.

There are two ways to register students for your CSAwesome custom course:
1.  Student-directed: Create your custom course with a unique name like SchoolName-2020. Tell your students to go  to https://runestone.academy/ and click on Sign Up and enter in the info to set up an account and enter Your Course Name (e.g. SchoolName-2020) into the Course Name field (clear the field first). Check the box next to “I agree” and click Sign Up.

2. Teacher-directed: If your students do NOT have runestone accounts already, you can upload a csv file (save any spreadsheet as a csv file) with rows of username, email, first_name, last_name, password, coursename in Instructor's Page/Admin/Manage Students. You get to make up their usernames and passwords and register them for runestone and your course. See https://www.runestoneinteractive.org/2019/10/25/privaterunestone.html on how to avoid PII and personal emails.

Hope that helps,
-Beryl
