### ISSUE TITLE
Bug with ordered lists showing up as left justified and not centered like the text

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#112]
The ordered lists are showing up left justified rather than in the center of the page like normal text.  This seems to be due to using a class of arabic simple on them  <ol class="arabic simple">

**Comment by bnmnetp** [comment]
Yeah,
This  was an unintended side effect of my 'fix' to make the exercises extra wide.

I have a better solution whereby we will simply indent the exercises inside a

```
.. container:: exercise_list
```
directive, but I haven't checked that in yet.  I'm just wondering if we should use a better class name than exercise_list because the container trick could be used anywhere that we want to have the text full width.

Suggestion?

**Comment by ericsonga** [comment]
I like this idea.  Why a exercise list?  Why not just an exercise directive?

**Comment by bnmnetp** [comment]
Only because it was really easy to use the built-in container directive.  As of a few days ago, anywhere you use:

```
.. container:: full_width

    your indented stuff here...

```
This just wraps all the indented stuff in an html div with the class full-width.   This is nice in that anything you want to have appear as a full width section of the book can be done like this.
