### ISSUE TITLE
Fix practice problems to log # correct and # incorrect. 

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneComponents#1132]
In the log file we can tell if a Parsons problem or multiple-choice question is correct, but not some of the other types of practice problems.  It would be great if all practice problems told you if they were correct or not or even better if they had a # correct out of # given so % correct could be used.

**Comment by bnmnetp** [comment]
We are already logging this in the xxx_answers tables.  I know that does not help your research as I have only been sending you what is in the useinfo table, but the information is there.

**Comment by barbarer** [comment]
Can you add the information when you dump a log or should we modify the problem types that currently only save the answer with no indication of how much of it is correct?  I am thinking we should make a consistent format of num correct/num given so that we can calculate the % correct for all problem types.  The problems types that we need to change are clickableArea, dragNdrop, and fillb.

**Comment by bnmnetp** [comment]
I believe all question types are reporting correctness as well as percent correct information.  If we change the format of the `act` field in the database then we need to make sure that we do not break the autograder or the recording of said information in the xxx_answer field.

I just made the change to have each component report the percent information a month or so ago, so it would not make sense at this time to re-dump logs for you.

**Comment by barbarer** [comment]
Could we just add another log entry with the score information?

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
I don't think it makes sense to add another log entry when we are already storing correctness in the xxx_answers tables.  I just checked and we are storing correctness.  Just not percentage (yet)

Maybe for your research purposes it makes sense to either include anonymized data from xxx_answers.

We just need to add a column for percentage.  

Blindly adding additional information to the act column is very likely to break something, so I don't want to do that until I can check things more carefully.  I was also trying to focus on getting this new book server up and running, rather than continuing to add to the old server.

**Comment by bnmnetp** [comment]
Also, having now checked what is actually being sent for a percentage we are sending just the percent value not the X out of Y information.

**Comment by bnmnetp** [comment]
Closing as percent is now stored for all problem types in xxx_answers and the autograder has been updated.
