### ISSUE TITLE
Active code in timed exams are showing has attempted (number buttons are shown in gray) when you just display them

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/RunestoneComponents#1138]
On a timed exam if you display an active code problem and then move on to the next problem and don't try to answer the active code problem the number button is turned gray for the active code problem since it seems to try to run the code even if you haven't edited the problem.
![Screen Shot 2021-02-12 at 4 21 43 PM](https://user-images.githubusercontent.com/43884467/107823859-80295080-6d4e-11eb-87d3-80cf50f93455.png)

**Comment by bnmnetp** [comment]
So, its very hard to determine.  If the only action a student takes is they press the run button should that count as skipped?  I made is so that running or typing would set the `isAnswered` flag.  But I can change it so that they have to modify the text in the editor in order for `isAnswered === true`

**Comment by bnmnetp** [comment]
I updated this as well.  The student must make some change to the code.  If no code is changed then it won't even run and will end up as skipped.
