### ISSUE TITLE
Need for better navigation

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#12]
We need to move the next and previous arrows to the top and bottom of the page.  Currently the arrows get put on top of the page text on cell phones.  They are also hard to see.  It would be great if we also had a breadcrumb trail of the hierarchy (chapter, section) and if we showed your progress through the chapter in some way (how many sections have you completed out of all the sections in a chapter).

**Comment by NateJose123** [comment]
Hey Brad @bnmnetp, 

Aaron, Tobi and I(Nathan) are working on implementing breadcrumbs in the books. We were wondering what directory/files would help us get the references to each page in the book.

Thanks.

**Comment by NateJose123** [comment]
Hello @bnmnetp ,

Aaron, Tobi and I are working on this and we were thinking about using the URL to generate links for the breadcrumbs and store these links in a list to update the breadcrumbs as necessary. Is there a simpler way of doing this/ do you have any ideas or suggestions on how to best implement this?

Thank you.

**Comment by bnmnetp** [comment]
Take a look at the books.py controller and see how we generate the data needed for the Chapter dropdown. I think you might have good luck doing something like that.

**Comment by NateJose123** [comment]
Hello @bnmnetp ,

We were just reviewing the breadcrumbs feature and found out that it might be redundant/unnecessary since all the books have the "This Chapter" button that provides easy access to all the subsections and none of the books go more than 3 layers deep with sub sections. Hence, we're wondering if this issue could be closed since the feature wouldn't be useful. Let us know what you think.

Thanks,

Aaron, Tobi and Nathan.
