### ISSUE TITLE
Today I updated the master for the JavaReview ebook - but the user interface isn't up to date

### ISSUE THREAD

**Issue by ericsonga** [RunestoneInteractive/RunestoneComponents#158]
I updated the JavaReview ebook master which did update the online version, but it didn't have my user interface changes to the short answer directive even though those were in the current version of RunestoneComponents.  Any idea why?

**Comment by bnmnetp** [comment]
The build always uses  the stable/released version of the components.  I have not made a new release with all of our hackweek goodness yet.  I will do that today or tomorrow.

**Comment by ericsonga** [comment]
Good to know.  Is there a way to know what version will be used so that I don't have to ask you before I update the master?

**Comment by bnmnetp** [comment]
So, actually, you do have control over this in the requirements.txt file for the book.  By default it will grab the latest version of runestone from pypi.python.org because in the the requirements.txt file it says ``runestone>=2.1.0``  You could say ``runestone==2.1.0`` and it will always fetch that version, or you could put ``runestone==git+git://github.com/RunestoneInteractive/RunestoneTools.git`` to have it always grab the latest from github.  But I wouldn't recommend that last just because I consider that less well tested.
