### ISSUE TITLE
assignment due date

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#247]
Error reported in course haugrud16f on page http://interactivepython.org/runestone/assignments/detail?id=955&sid=60091 by user haugrudm haugrudm@mnstate.edu
Last semester (before the activecode history enhancement), students could not save modified code after the specified due date/time. Now they can save modified code after the due date/time. When I grade an activecode exercise, there is a Load History button but it is non-functional. The code that does appear for grading is the version most recently run/saved by the student - even if it was saved after the due date. This makes due date meaningless. Either disabling saving after the due date or giving the instructor the ability to load history would solve this problem.

**Comment by bnmnetp** [comment]
Hmmm, @presnick are you seeing this same thing in the old interface?  I'm not sure why the show history button would not work.

**Comment by presnick** [comment]
Just checked and the Load History button doesn't work in the old grading interface.

I think we should either:
1. make the grading interface load only code before the due date OR
2. disable saving of code after the due date

I'm a little concerned with #1 that if we allow saving after the due date, it will be confusing to students that they get comments but it's not for their latest code. If we decide to go this route, I'm probably the right one to implement.

With #2, we would need to do something to notify students that their latest code wasn't saving. That's a RunestoneComponents thing that you're probably in the best position to implement, Brad.

**Comment by bnmnetp** [comment]
The thing is that I don't like to have the system impose a particular model of how to handle late work.  You and mike are pretty severe in book.  I'm pretty lax about late work as I would rather have them get the work done and get the benefit of doing the assignment as opposed to not be able to complete the assignment because saving is disabled.  My policy is typically if you get it done by the time I grade it, it's on time.  After that you might not get any credit.  Of course they don't know when I'll get around to grading it, so it's a bit of a risk.  Others are somewhere in between the two extremes.  

In my view the history slider should work and then the instructor or TA can decide what version to grade.

**Comment by presnick** [comment]
Fair enough. I think the instructor should at least be able to set a flag in the grading interface to query for the latest prior to deadline.

I think this also argues in favor of my proposal for associating comments with questions rather than particular code submissions. If the instructor grades an earlier version, students are likely to miss it if it's associated with the code rather than the question. https://github.com/RunestoneInteractive/RunestoneServer/issues/840

**Comment by bnmnetp** [comment]
We need to make sure there is a way to specify this and is account for this in the new assignment and grading interface.

**Comment by presnick** [comment]
We already have a checkbox for whether to autograde work submitted after the deadline. I think we could have the manual grader, when it loads an answer (code or mchoice or whatever) automatically go to the last answer before the deadline, or the last answer overall, depending on the state of the checkbox.  I think this should be handled in jscript in the client, but if you want the server to send some indicator of which answer to start the scrubber on, that's a possibility also.

**Comment by bnmnetp** [comment]
I agree, but I'm not seeing a checkbox.  Is this still in the design but not implemented category or should I be seeing it in the combined efforts of you and Bryan?

**Comment by presnick** [comment]
It's been there for a while, on /runestone/admin/grading. Left side,
labeled, "Only check work submitted before assignment deadline".

It's still there for me.

**Comment by bnmnetp** [comment]
Oh, gotcha.  I was thinking of it as part of the assignment definition.

**Comment by bnmnetp** [comment]
Now I'm looking at it from the activecode grading perspective.  I can deal with it by positioning the slider, but I need to know the deadline for the assignment that is displayed.  Is that stored somewhere convenient for me??

**Comment by presnick** [comment]
Well, the due_date is returned from the server when a call is made to get_assignment. (see, for example, admin.js line 1178). But that seems to happen only in the assignments interface. 

You can make a call to that endpoint when someone selects an assignment in the grading interface, and then display that deadline near the checkbox. With that endpoint you're getting a whole lot of extra info about the assignment (e.g., the question names) that is currently getting fetched as part of the page itself. Another option is to pass the deadlines for all the assignments in the dictionary that is sent from admin.py/grading()
