### ISSUE TITLE
Missing Example Program

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#320]
Error reported in course thinkcspy on page 03_widgets by user armitag8 joe.armitage@mail.utoronto.ca
The example program (all_user_input_widgets.py) is missing at:

http://interactivepython.org/runestone/static/thinkcspy/GUIandEventDrivenProgramming/programs/all_user_input_widgets.py

**Comment by bnmnetp** [comment]
You two look into this one and let me know what you think should be done.

**Comment by conzty01** [comment]
We have determined that when the thinkcspy book is built via 'runestone build', that the folder path _sources/GUIandEventDrivenPrgramming/Programs is not placed into the build like the Figures folder containing the images for the page is.  To make a long story short, if the Programs folder is placed within the build next to the html files, and the "P" is changed to a lowercase, that the files link properly.

From what we could tell, when the book is built, the interpreter moves the files in the Figures folder to the _images folder of the build and links to them properly when it creates the html file for a given page.  However, nothing of the sort occurs for the Programs folder and none of those files are moved to the build causing the link to 404.

To fix this, we believe that the interpreter should be altered so that similar to how figures are transfered to the build, programs-- or rather any generic folder really-- can be moved to a _programs or _other folder in the _static folder of the build and linked from the html files by way of '../_programs/<filename>' .

**Comment by bnmnetp** [comment]
Modifying sphinx is not really an option.

I think you will need to look into making programs a static folder so that all those files get copied into _static.  Then the links in the source should be changed to point there rather than to Programs/xxxxxx
