### ISSUE TITLE
reading assignment

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#441]
Error reported in course java on page /runestone/assignments/doAssignment?assignment_id=108 by user dstephens diane.stephens@ung.edu
Please describe what you were doing that led up to this error: I am creating assignments for my 'java' course.  It looks like if any reading assignments are included in an assignment you get this error page when selecting the assignment from the assignments link at the top of the index.  If I remove the reading portions of the assignment, the error is not generated.

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 1295, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 409, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 1221, in doAssignment
    chapterPath = (completion.chapter_id + '/toctree.html')
AttributeError: 'NoneType' object has no attribute 'chapter_id'

**Comment by bnmnetp** [comment]
Which java course?  The JavaReview course or the Java for Python programmers?

I've not seen this problem in another class, but I'll take a look and see what I can figure out.

**Comment by bnmnetp** [comment]
I think I have solved it.

The good news is that I don't think it would have affected your students, but it was affecting you as the instructor, especially an instructor with multiple courses.  Some database tables used for tracking progress were not being set up due to one path through the code.  I've fixed that path.  You should go to the "Change Course" menu and re-select your course.  All should be well after that.
