### ISSUE TITLE
Jobe server used in runestone accepts http requests only

### ISSUE THREAD

**Issue by DaveParillo** [RunestoneInteractive/RunestoneComponents#513]
Runestone is currently configured to use a remote server setup for the University of Canterbury, NZ, not particularly runestone.
Because the jobe server accepts http only, this creates a barrier for publishing runestone content on GitHub pages, for example. See [github help](https://help.github.com/articles/securing-your-github-pages-site-with-https/#resolving-problems-with-mixed-content).

Ideally, there would exist a Jobe server on https.  Less than ideally, all requests to jobe could go through a proxy like [cors-anywhere](https://cors-anywhere.herokuapp.com/).

**Comment by bnmnetp** [comment]
I agree, we added the Jobe server because it was offered to us, and was FREE.   Spinning up a Jobe server of our own will cost $ as we'll need more server power, either another droplet on Digital Ocean or a larger one. I need to investigate traffic and load issues. 

I think the experiment has proven successful in as much as we are seeing good use of the Java based books, and it seems you are working on C++.  Currently I'm proxying the server for all of the requests that come from courses hosted on runestone.academy.

**Comment by bnmnetp** [comment]
I just accepted #505 This will allow you to configure your book to use whatever JOBE server you want.  You could run your own simple https proxy, or maybe we can find a way to let you use runestone as a proxy without opening up JOBE to potentially malicious users.

**Comment by DaveParillo** [comment]
Since it's so easy to set up a proxy, which clearly works fine, I suggest the runestone docs for the active code directive explain this and we just close this issue as not needed.
