### ISSUE TITLE
Ampersand in Assignment name causes problems

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#535]
I tried to create an assignment with a title like
Reading & Exercise
but the ampersand causes problems and the system goes into a wacky state where I can't add or delete components and nothing really gets saved. I already had an assignment with the name Reading, which I think contributed to the problems.

It's not that I need the ampersand in the name, but it would be nice if this were dealt with cleanly, either by allowing or else with an explicit error message saying not to do it.

**Comment by bnmnetp** [comment]
Agreed.  It should not be too hard to write a validation method either in Javascript, or on the server side to ensure that the assignment name does not have an ampersand in it.

In the meantime, I can update the name for you and replace & with and

**Comment by bnmnetp** [comment]
I looked and I cannot find an assignment named 'Reading & Exercise' . Did you delete it?

**Comment by cigas** [comment]
I already made the change (and the actual name is a bit longer)

**Comment by knakaj** [comment]
We tried to replicate the error so that we could see what needed to be fixed. Although we created a few assignments with the "&" on the Assignment name, we didn't get any errors. We were able to add and remove components from the assignment, as well as successfully save the student progress. More clarification on the step that leads to the error would be helpful.

**Comment by cigas** [comment]
This seems to have gotten fixed as a byproduct of other changes. It has been 4.5 years since I originally filed this. I tried it again and there doesn't seem to be a problem anymore. Let's close this an be done with it.
