### ISSUE TITLE
Not Authorized

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#806]
Error reported in course StudentCSP on page index by user Patrick008 patrick.cummins@bexleyschools.org
Hi, I am an educator that currently uses two of your courses, one of the courses "StudentCSP" will not allow me to view its progress page and says I am " not authorized". 

Is ther any way you can change this so I can see the progress of my students.

Thank you so much, and your site is awesome :)

Patrick

**Comment by bnmnetp** [comment]
Hi Patrick,

I’m glad you like our work!  You are not authorized to see the instructor page for either StudentCSP or apcsareview because anybody can register for those courses.  In fact thousands of people are registered for them and you would be privy to all the work of all of them and then we would both be guilty of violating FERPA rules.

The best way to use Runestone with your own students is to create your own course(s) based on the books you want to use.  Please take a look at https://runestone.academy/runestone/static/instructorguide/index.html It has instructions and some videos that will help you get started.
