### ISSUE TITLE
Resizing of ActiveCode window

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/RunestoneComponents#853]
In the new update, Java active code windows can't be resized past the output window. This is good because they don't overlap anymore, but it's also bad because it makes it very frustrating to see all of your code and make changes. You can only see about half a line of code at a time. Is it possible to make the output window resizable too or to have a button to make it disappear when you're working on the code? 
Thanks! 
-Beryl

![image](https://user-images.githubusercontent.com/4571962/61194531-1176a380-a690-11e9-803f-558dafc0a252.png)

**Comment by bnmnetp** [comment]
Hi Beryl,

I don’t think that was an intentional change.  The arrangement of these windows and the CSS that controls their width has always been a bit of a challenge to get right.

The easiest thing to do would be to always have the output appear under the code, but sometimes that can lead to problems with students not seeing the output.  Maybe less of a problem now than it was in the early days. 

We have not revisited the visual design of the activecode component for a while, so maybe now is a good chance to think about what would be best and to update activecode.

I’m on vacation this week, but will be back at it next week.

**Comment by bhoffman0** [comment]
What if the output window was above the code window? Students would see it, and there would be no resizing problems.

**Comment by bnmnetp** [comment]
As I've been thinking about it, I really think we can put it below the editor all the time.  Early in the book this is really just a matter of a very short learning curve for students to know that the output will come below the code.

I'm not in favor of above the code as it would separate the run button from the code by too much.

**Comment by bnmnetp** [comment]
I updated components to simplify this so that the output window always appears below the editor.  The change is live now, so let me know if you see any problems.
