### ISSUE TITLE
minimal_outside_links hiding instructor's page

### ISSUE THREAD

**Issue by donnerc** [RunestoneInteractive/RunestoneComponents#925]
The `minimal_outside_links` flag that can be specified in `pavement.py` is very handy to hide all external links. But why in the world hide the instructors page and things like Edit Password ? It would be nice to have such a flag to disable social network stuff but still have the instructor and other similar links in the "user" menu.

**Comment by bnmnetp** [comment]
This was added by @presnick and I'm pretty sure its for when Runestone is used in conjunction with Coursera.... Paul can correct me if I'm wrong.  In their case the password management and grading and assignments are external to Runestone.

**Comment by presnick** [comment]
Yes, we hide a bunch of stuff that confuses students and leads them to do wrong things. For example, if they are getting automatically authenticated from an LMS (Canvas or Coursera), we don't want them to edit their profile or password.

Hiding the instructor page link was just because it was confusing to students, and I didn't see an easy way to make the inclusion of that link conditional on the user having instructor privileges.

Note that this flag is not used on the Runestone Academy installation.

**Comment by donnerc** [comment]
Ok, I fully understand. Thanks for the explanation. I probably will add yet another flag on my side to accomodate my own needs.
