### ISSUE TITLE
Cannot grade assignments

### ISSUE THREAD

**Issue by dianeroux** [RunestoneInteractive/RunestoneComponents#939]
It looks like the Grading page has changed in How to Think Like a Computer Scientist and I can no longer grade the assignments I created at the beginning of the term.

This is one of the assignments:
![Ch4](https://user-images.githubusercontent.com/32103576/66702958-46b87f00-ecdb-11e9-8bb2-767e108b57ed.PNG)

And I get "Not Released" when I try to grade it:
![Ch4Grading](https://user-images.githubusercontent.com/32103576/66702979-79627780-ecdb-11e9-9232-427ab9f08655.PNG)

Suggestions?

**Comment by dianeroux** [comment]
Sorry.  It works.  I was distracted by the "Not Released" message in red.

**Comment by bnmnetp** [comment]
Hopefully you will find this update to be more streamlined and a real improvement.  The Not Released message is because many instructors told me it was too easy to forget to click the Release Grades to students Button.
Lots of updates this week, they are now live.  The main things to look for include:


2. I have plugged a couple of holes in session handling, where students could mistakenly end up in the open fopp book instead of in the correct course.
3. In addition, if the student is not logged in, the progress bar at the bottom of the page will be gray instead of green.  Another visual indicator that they are not logged in.
4. The grading interface has been redesigned into a new layout, and streamlined significantly.  
	1. Now you only have one choice to make.  Start with either a Chapter or an Assignment.
	2. Questions for chapters are sorted alphabetically
	3. Its easy to select all question or all students or both.
	4. Chapters, Assignments, Questions, and students are all searchable.  So if you have a class of 125 and need to regrade that one student it is easier to find them.
	5. If an assignment has not had its grades released there is a bright red message to that effect that will remind you to press the button.
	6. If you select multiple students you can navigate from score to score with the tab key and when you update the score it autosaves when you move to the next input field.  You’ll know it has saved because it will turn light green. 
	7. If you like grading things one at a time, the old save and save/next buttons are still there.

Hopefully this fixes more things than it breaks!  Let me know how it works.

You should join our slack channel as I regularly post about updates like these there.

**Comment by dianeroux** [comment]
Thanks for the update.  I'll start monitoring the slack channel.  Diane

________________________________
